# Generated by Django 3.0.7 on 2020-06-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('detalles', models.TextField()),
                ('fasta_file', models.FileField(upload_to='fastas')),
            ],
        ),
    ]
