# Generated by Django 3.0.7 on 2020-06-22 11:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastaentry',
            name='fasta_file',
            field=models.FileField(upload_to=api.models.get_fasta_path),
        ),
    ]
