# Generated by Django 3.0.7 on 2020-07-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200704_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastaentry',
            name='alignament_file',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
