# Generated by Django 3.0.7 on 2020-07-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200716_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastaentry',
            name='newick_tree',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
